config/routes.rb
Yblog::Application.routes.draw do
  resources :polls

  resources :points

  get "admin" => 'admin#index'

  get "contadores" => 'front#contadores'

  devise_for :users

  root 'front#index'

end

app/models/point.rb
class Point < ActiveRecord::Base

	validates :lat, :long, presence: true, uniqueness: true
	validates :title, presence: true

end

app/models/poll.rb
class Poll < ActiveRecord::Base

	scope :recent, -> {order('created_at desc')}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!

  def index
		@body_class = "admin"
		@puntos = Point.count
		@encuestas = Poll.count  	
  end

  def points
		@body_class = "admin"  	
  	
    @points = Point.all	
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
	before_action :list_markers

  require 'open-uri'
  # require "json"

  def index

    # @t_followers = TWITTER.followers("hola_yadira").count + TWITTER.followers("holaarandas").count

    # tweets_hola_yadira = TWITTER.search("to:hola_yadira", result_type: "all").take(10)
    # tweets_holaarandas = TWITTER.search("to:holaarandas", result_type: "all").take(10)

    # @recent_tweets = TWITTER.search("to:hola_yadira", result_type: "recent").take(20)

  	@list_markers = list_markers
    @marker_info = Point.all
    @poll = Poll.first
  end


  def contadores
    @body_class = "contadores" 
    # file1 = open("https://twitter.com/<%= TWITTER_USERNAME1 %>")
    # @doc = Nokogiri::HTML(file) do |config|
    #   config.nonet.noerror
    # end

    holaarandas = Nokogiri::HTML(open("https://twitter.com/#{TWITTER_USERNAME1}"))
    hola_yadira = Nokogiri::HTML(open("https://twitter.com/#{TWITTER_USERNAME2}"))
    instagram_hola_yadira = Nokogiri::HTML(open("https://instagram.com/hola_yadira"))

    @amigos_holaarandas = holaarandas.at_css("#page-container > div.ProfileCanopy.ProfileCanopy--withNav > div > div.ProfileCanopy-navBar > div > div > div.Grid-cell.u-size2of3.u-lg-size3of4 > div > div > ul > li.ProfileNav-item.ProfileNav-item--followers > a > span.ProfileNav-value")
    @amigos_hola_yadira = hola_yadira.at_css("#page-container > div.ProfileCanopy.ProfileCanopy--withNav > div > div.ProfileCanopy-navBar > div > div > div.Grid-cell.u-size2of3.u-lg-size3of4 > div > div > ul > li.ProfileNav-item.ProfileNav-item--followers > a > span.ProfileNav-value")

    g = instagram_hola_yadira.xpath("//script").text
    # url = open("http://www.reddit.com/.json").read
    f = (/followed_by/ =~ g)
    final = /follows/ =~ g[f..-1] 
    # inicio = f + 12
    @contenido = g[f+13,final-15]
    # @contenido = JSON.parse(url)["kind"]
  
  end

  def list_markers
  	@markers = Point.all

  	list = []
  	@markers.each do |m|
  		ui = [m.title.to_s, m.lat.to_f, m.long.to_f]
  		list <<  ui
  	end

  	list
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html, :json
  
  def index
    @body_class = 'admin'
    @points = Point.all
    respond_with(@points)
  end

  def show
    @body_class = 'admin'
    respond_with(@point)
  end

  def new
    @body_class = 'admin'

    @point = Point.new
    respond_with(@point)
  end

  def edit
    @body_class = 'admin'

  end

  def create
    @point = Point.new(point_params)
    @point.save
    respond_with(@point)
  end

  def update
    @point.update(point_params)
    respond_with(@point)
  end

  def destroy
    @point.destroy
    respond_with(@point)
  end

  private
    def set_point
      @point = Point.find(params[:id])
    end

    def point_params
      params.require(:point).permit(:lat, :long, :title, :desc)
    end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html, :json
  

  def index
    @body_class = "admin"   

    @polls = Poll.recent
    respond_with(@polls)
  end

  def show
    @body_class = "admin"   

    respond_with(@poll)
  end

  def new
    @body_class = "admin"   

    @poll = Poll.new
    respond_with(@poll)
  end

  def edit
    @body_class = "admin"   
    
  end

  def create
    @poll = Poll.new(poll_params)
    @poll.save
    respond_with(@poll)
  end

  def update
    @poll.update(poll_params)
    respond_with(@poll)
  end

  def destroy
    @poll.destroy
    respond_with(@poll)
  end

  private
    def set_poll
      @poll = Poll.find(params[:id])
    end

    def poll_params
      params.require(:poll).permit(:point)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/admin/_nav.html.erb
<!-- Fixed nav -->
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><%= SITE_TITLE %></a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if current_page?(admin_path) %>"><%= link_to 'Home', admin_path %></li>
            <li class="<%= 'active' if current_page?(points_path) %>"><%= link_to 'Puntos', points_path %></li>
            <li class="<%= 'active' if current_page?(polls_path) %>"><%= link_to 'Encuestas', polls_path %></li>

            
          </ul>

          <!-- right side of nav -->
          <ul class="nav navbar-nav navbar-right">
          	<li>
              <a href="<%= root_path %>" class="fix">
                <i class="fa fa-share" data-toggle="tooltip" data-placement="bottom" title="ir a sitio"></i>
              </a>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: "fix" do %>
                <i class="fa fa-sign-out" data-toggle="tooltip" data-placement="bottom" title="salir"></i>
              <% end %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/admin/index.html.erb
<%= render 'nav' %>

<div class="container text-center">

	<div class="inline-div">
		<h2><%= @puntos %></h2>
		<p>Puntos</p>
	</div>

	<div class="inline-div">
		<h2><%= @encuestas %></h2>
		<p>Encuestas</p>
	</div>
	
</div>

app/views/admin/points.html.erb
<h1>Listing points</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Long</th>
      <th>Title</th>
      <th>Desc</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>
        <td><%= point.lat %></td>
        <td><%= point.long %></td>
        <td><%= point.title %></td>
        <td><%= point.desc %></td>
        <td><%= link_to 'Show', point %></td>
        <td><%= link_to 'Edit', edit_point_path(point) %></td>
        <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point', new_point_path %>

app/views/front/contadores.html.erb
<p>
	<b>@holaarandas: </b>
	<%= @amigos_holaarandas.text %>
</p>
<p>
	<b>@hola_yadira: </b>
	<%= @amigos_hola_yadira.text %>
</p>
<p>
	<b>/hola_yadira instagram: </b>
	<%= @contenido %>
</p>

app/views/front/index.html.erb
<%= render 'shared/nav' %>

<div class="site-wrapper" id="inicio">
      <%= image_tag 'cover.jpg', class: "clearfix" %>
</div>

<section id="video" class="">
    <video autoplay muted loop>
        <source src="https://dl.dropboxusercontent.com/u/32178315/holayadira/MVI_6789.mp4" type="video/mp4">
        Your browser does not support the video tag      
    </video>
</section>
<section id="info" class="padding-b">

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="h-container block-center">
                    <h2 class="upper white"><b>Hola</b><br>soy yadira</h2>
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="">
                    <br><br>
                    <div class="box-info">
                        <h4>Datos personales:</h4>
                        <div class="box-border">
                            <p>Yadira del Carmen Guzmán Alvizo.</p>
                            <p>Arandense de nacimiento, de corazón y por vocación.
                            </p>
                            <p>Tengo 34 años.
                            </p>   
                            <p>Casada con Carlos, mamá de Monse y de Mariana.</p>
                        </div>
                    </div>
                    <br>
                    <div class="box-info">
                        <h4>Puesto solicitado:</h4>
                        <div class="box-border">
                            <p>Ser el mejor presidente de la historia de Arandas.</p>
                        </div>
                    </div>
                    <div class="box-info">
                        <h4>Formación académica:</h4>
                        <div class="box-border">
                            <p><b>Licenciatura:</b> Centro Universitario de los Altos.</p>
                            <p>Licenciatura en Administración.</p>
                            <p>2000 - 20004</p>
                            <p><b>Maestría:</b> Instituto Superior de Estudios para la familia. Universidad Anáhuac.</p>
                            <p>Maestria en Ciencias de la Familia.</p>
                            <p>2010 - 2013</p>
                        </div>
                    </div>
                    <div class="box-info">
                        <h4>Experiencia profesional:</h4>
                        <div class="box-border">
                            <p><b>Directora general:</b> Instituto Alteño para el Desarrollo de Jalisco, AC.</p>
                            <p>2009 - 2014</p>
                            <p><b>Coordinador técnico administrativo:</b> Agencia de Desarrollo Rural validado por la UTN-FAO. PESA-FAO (Organización de las Naciones Unidas para la Alimentación y la Agricultura.</p>
                            <p>2009 - 2010</p>
                            <p><b>Directora general:</b> Sistema para el Desarrollo Integral de la Familia. DIF Arandas.</p>
                            <p>2007 - 2009</p>
                        </div>
                    </div>
                      
                </div>
            </div>
            <div class="col-md-6 col-sm-6 hidden-xs">
                    <br><br>
                    <div class="box-info">
                        <h4>Otros estudios y actividades:</h4>
                        <div class="box-border">
                            <p>Diplomado en Capacidades Directivas, 2011.</p>
                            <p>Capacitación en Implementación de Gestión de Calidad ISO 9001:2008 en el 2012.</p>
                            <p>Congreso Internacional de la Familia, ediciones del 2007 al 2011.</p>
                            <p>Taller 'Habilidades Directivas', 2002.</p>
                            <p>Diplomado en Orientación Familiar, 2008 - 2009.</p>
                            <p>Taller 'Toma de Decisiones en Consenso', 2014.</p>
                            <p>Diplomado en Habilidades y Técnicas de la Comunicación, 2014.</p>
                        </div>
                    </div>
                    <div class="box-info">
                        <h4>Aptitudes y habilidades:</h4>
                        <div class="box-border">
                            <p>Comprometida con mi trabajo, exigente con mis resultados y con el de la gente que me rodea.</p>
                            <p>Mis 3 libros favoritos (<b><u>yo sí me acuerdo</u></b>) son 'El Hombre en busca del sentido' de Viktor Frankl, 'En busca de respuestas' de Felipe González y 'Mi planta de naranja lima' de Vasconcelos.</p>
                            <p>Soy buena hablando en público, pero -tengo que reconocerlo- muy mala dibujando.</p>
                            <p>Mi color favorito es el azul, aunque sea coincidencia.</p>
                        </div>
                    </div>
                <!-- <div class="cont-img">
                    <%= image_tag 'person.svg', class: "img-flex" %>
                </div> -->
            </div>
        </div>
    </div>
</section>

<div class="back back-fixed1 text-center">
    <div class="container-fluid">
        <h3>"La democracia es el gobierno del pueblo, por el pueblo y para el pueblo"</h3>
        <p>- Abraham Lincoln</p>
    </div>
</div>



<section class="" id="ruta">

    <div class="">
        <div class="row">
            <div class="col-lg-12 col-sm-12 col-xs-12 text-center">
                <div class="cont-text-map">
                    <div class="recorrido text-center">
                        <%= image_tag 'distance.svg', class: "img-flex" %>
                    </div>
                    <h2 class="">Recorrido del día de Yadira</h2>
                    
                </div>

            </div>
            <div class="col-lg-12 col-sm-12 col-xs-12 ">
                <div id="map_wrapper">
                    <div id="map_canvas" class="mapping">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="back back-fixed2 text-center">
    <div class="container-fluid">
        <h3>"La democracia no es el silencio, es la claridad con que se exponen los problemas y la existencia de medios para resolverlos."</h3>
        <p>- Enrique Múgica Herzog</p>
    </div>
</div>


<section id="vota" class="padding-b">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-4 col-xs-12 text-center">
                <div class="vote text-center">
                    <%= image_tag 'vote1.svg', class: "img-flex" %>
                </div>
                <h2 class="text-center">Democracia participativa</h2>
                
            </div>
            <div class="col-lg-8 col-sm-8 col-xs-12">
                <% if @poll %>
                  <div id="debate_1_<%= @poll.point %>"></div>
                  <script>
                    (function () {
                      var opst = document.createElement('script');
                      var os_host = document.location.protocol == "https:" ? "https:" : "http:";
                      opst.type = 'text/javascript';
                      opst.async = true;
                      opst.src = os_host + '//' + 'www.opinionstage.com/polls/<%= @poll.point %>/embed.js';
                      (document.getElementsByTagName('head')[0] ||
                        document.getElementsByTagName('body')[0]).appendChild(opst);
                    }());
                  </script>
                <% end %>
            </div>
        </div>
    </div>
</section>

<section id="contacto" class="padding-b">
    <div class="container text-center">
        <div class="row">
            <div class="col-lg-4"></div>
            <div class="col-lg-4">
                <h3 class="upper2"><b>contacto</b></h3>

            </div>
            <div class="col-lg-4"></div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <%= image_tag 'pan.png', class: "img-flex img-footer" %>
            </div>
            <div class="col-lg-4 col-sm-12 col-xs-8 col-md-12 contacto-mail">
                <p class="text-center">Muchos caminos conducen a Yadira. Los más rápidos son los siguientes. 
                </p>
                <a href="mailto:<%= EMAIL %>">
                    <div class="button y"><%= EMAIL %></div>
                </a>
                <a href="mailto:<%= EMAIL2 %>">
                    <div class="button y"><%= EMAIL2 %></div>
                </a>
            </div>
            <div class="col-lg-2 col-sm-12 col-xs-12">
                <div class="row-m">
                    <a href="https://twitter.com/<%= TWITTER_USERNAME1 %>" data-toggle="tooltip" data-placement="top" title="@hola_yadira">
                        <div class="bttn blue-t">
                            <%= image_tag 'twitter.svg' %>
                        </div>
                    </a>
                    <a href="<%= FACEBOOK_URL2 %>" data-toggle="tooltip" data-placement="top" title="Yadira Guzmán">
                        <div class="bttn blue-f">
                            <%= image_tag 'face.svg' %>
                        </div>
                    </a>
                 
                </div>
               <div class="row-m">
                    <a href="<%= YOUTUBE %>" data-toggle="tooltip" data-placement="top" title="Hola Arandas">
                        <div class="bttn red-y">
                            <%= image_tag 'youtube.svg' %>
                        </div>
                    </a>
                    <a href="https://vine.co/u/1193340633595707392" data-toggle="tooltip" data-placement="top" title="Hola Yadira">
                        <div class="bttn green-v">
                            <%= image_tag 'vine.svg' %>
                        </div>
                    </a>
                    
                </div>
               
                <div class="row-m">
                    <a href="https://instagram.com/hola_yadira/" data-toggle="tooltip" data-placement="top" title="hola_yadira">
                        <div class="bttn blue-f">
                            <%= image_tag 'instagram.svg' %>
                        </div>
                    </a>
                </div>

                
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>
</section>

<footer class="footer">
    <div class="container">
        <p class="text-muted">Copyright todos los derechos reservados 2015</p>
    </div>
</footer>
























<script type="text/javascript">
	$(function(){
	// cargar el mapa asincrono

	var script = document.createElement('script');
	script.src = "http://maps.googleapis.com/maps/api/js?sensor=false&callback=initialize";
	document.body.appendChild(script);

});



function initialize() {
    var map;
    var bounds = new google.maps.LatLngBounds();
    var mapOptions = {
        mapTypeId: 'roadmap',
        scrollwheel: false,
        zoomControl: true,
        panControl: false,
        mapTypeControl: false,
        streetViewControl: true,
        zoomControlOptions: {
            style: google.maps.ZoomControlStyle.SMALL,
            position: google.maps.ControlPosition.RIGHT_BOTTOM
        }
    };
                    
    // Display a map on the page
    map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
    map.setTilt(45);
        
    // Multiple Markers


    var markers = <%= raw @list_markers %>

    var infoWindowContent = [
        <% @marker_info.each do |m| %>
            ['<div class="info_content">' + '<h3><%= m.title %></h3>' + '<p><%= m.desc %></p>' + '</div>'],
        <% end %>
    ]

        
    // Display multiple markers on a map
    var infoWindow = new google.maps.InfoWindow(), marker, i;
    
    // Loop through our array of markers & place each one on the map  
    for( i = 0; i < markers.length; i++ ) {
        var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
        bounds.extend(position);
        marker = new google.maps.Marker({
            position: position,
            map: map,
            title: markers[i][0]
        });
        
        // Allow each marker to have an info window    
        google.maps.event.addListener(marker, 'click', (function(marker, i) {
            return function() {
                infoWindow.setContent(infoWindowContent[i][0]);
                infoWindow.open(map, marker);
            }
        })(marker, i));

        // Automatically center the map fitting all markers on the screen
        map.fitBounds(bounds);
    }

    // Override our map zoom level once our fitBounds function runs (Make sure it only runs once)
    var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function(event) {
        this.setZoom(11);
        google.maps.event.removeListener(boundsListener);
    });
    
}
	
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
  <title><%= SITE_TITLE %></title>
  <meta name="description" content="<%= META_DESCRIPTION %>">
  <meta name="keywords" content="<%= META_KEYWORDS %>">
  <link rel="shortcut icon" href="<%= asset_path 'y-fav.png' %>">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <%= csrf_meta_tags %>
</head>
<body class="<%= @body_class ? @body_class : 'default' %>">

<main class="cd-content">
	<%= yield %>
</main>	

<div class="cd-overlay-nav">
		<span></span>
</div> <!-- cd-overlay-nav -->

<div class="cd-overlay-content">
		<span></span>
</div> <!-- cd-overlay-content -->

<% if current_page?(root_path) %>
	<a href="#0" class="cd-nav-trigger">Menu<span class="cd-icon"></span></a>
<% end %>

</body>
</html>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :lat, class: "form-control", placeholder: 'lat' %>
  </div>
  <div class="field">
    <%= f.text_field :long, class: "form-control", placeholder: 'long' %>
  </div>
  <div class="field">
    <%= f.text_field :title, class: "form-control", placeholder: 'titulo' %>
  </div>
  <div class="field">
    <%= f.text_area :desc, class: "form-control", placeholder: 'descripcion' %>
  </div>
  <div class="actions">
    <%= f.submit 'crear', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/points/edit.html.erb
<%= render 'admin/nav' %>

<div class="container">
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>
</div>

app/views/points/index.html.erb
<%= render 'admin/nav' %>

<div class="container table-responsive">
  <div>
    <h1>Puntos</h1>
    <%= link_to 'Punto nuevo', new_point_path, class: "button pull-right" %>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Latitud</th>
        <th>Longitud</th>
        <th>Titulo</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @points.each do |point| %>
        <tr>
          <td><%= point.lat %></td>
          <td><%= point.long %></td>
          <td><%= point.title %></td>
          <td class="edicion">
            <%= link_to point do  %>
              <i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="ver"></i>
            <% end %>
            <%= link_to edit_point_path(point) do  %>
              <i class="fa fa-edit" data-toggle="tooltip" data-placement="top" title="editar"></i>
            <% end %>
            <%= link_to point, method: :delete, data: {confirm: "Estas seguro?"} do  %>
              <i class="fa fa-remove" data-toggle="tooltip" data-placement="top" title="destruir"></i>
            <% end %>


          </td>
          
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/points/new.html.erb
<%= render 'admin/nav' %>

<div class="container">

	<h1>Punto nuevo</h1>

	<%= render 'form' %>

</div>

app/views/points/show.html.erb
<%= render 'admin/nav' %>

<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @point.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @point.long %>
</p>

<p>
  <strong>Title:</strong>
  <%= @point.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @point.desc %>
</p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>
</div>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :point, class: "form-control", placeholder: 'id' %>
  </div>
  <div class="actions">
    <%= f.button 'crear', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<%= render 'admin/nav' %>
	
<div class="container">
	<h1>Editing poll</h1>

	<%= render 'form' %>


</div>	

app/views/polls/index.html.erb
<%= render 'admin/nav' %>

<div class="container table-responsive">

  <h1>Encuestas</h1>
  <p>Recuerda que la encuesta que se muestra en el frontpage es solo el id más reciente.</p>
  <p>Los id's de las encuestas los puedes generar en la siguiente página <a href="http://www.opinionstage.com/profiles/hola_yadira/dashboard">Opinion Stage</a></p>
  <p>user: hola_yadira</p>
  <p>password: 19891001abc </p>
  <%= link_to 'Nuevo id de encuesta', new_poll_path, class: "button pull-right" %>


  <table class="table table-hover">
    <thead>
      <tr>
        <th>id</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @polls.each do |poll| %>
        <tr>
          <td><%= poll.point %></td>
          
          <td class="edicion">
            <%= link_to poll do %>
              <i class="fa fa-eye" data-toggle="tooltip" data-placement="top" title="ver"></i>
            <% end %>
            <%= link_to edit_poll_path(poll) do %>
              <i class="fa fa-edit" data-toggle="tooltip" data-placement="top" title="editar"></i>
            <% end %>
            <%= link_to poll, method: :delete, data: { confirm: 'Estas seguro?'} do %>
              <i class="fa fa-remove" data-toggle="tooltip" data-placement="top" title="destruir"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/polls/new.html.erb
<%= render 'admin/nav' %>

<div class="container">

	<h1>New poll</h1>

	<%= render 'form' %>

</div>

app/views/polls/show.html.erb
<%= render 'admin/nav' %>
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>id:</strong>
	  <%= @poll.point %>
	</p>

	<%= link_to 'Edit', edit_poll_path(@poll) %> |
	<%= link_to 'Back', polls_path %>
</div>

app/views/shared/_nav.html.erb
<nav>
		<ul class="cd-primary-nav">
			<li><a class="nav" href="#inicio">Inicio</a></li>
			<li><a class="nav" href="#info">Datos de la presidenta</a></li>
			<li><a class="nav" href="#ruta">Ruta del día</a></li>
			<li><a class="nav" href="#vota">Democracia participativa</a></li>
			<li><a class="nav" href="#contacto">Contacto</a></li>
		</ul>
</nav>